export default {
  target: 'static',
  head: {
    title: 'SMASH',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      {
        name: 'viewport',
        content: 'width=device-width, initial-scale=1',
      },
    ],
    link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }],
  },
  css: [],
  plugins: [],
  components: false,
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    '@nuxtjs/tailwindcss',
    'nuxt-purge-icons-module',
    '@nuxtjs/device',
    '@nuxt/image',
    '@aceforth/nuxt-netlify',
    '@luxdamore/nuxt-humans-txt',
  ],
  modules: [
    '@nuxt/content',
    '@nuxtjs/markdownit',
    '@nuxt/image',
    [
      'nuxt-social-meta',
      {
        url: 'geosmash.net',
        title: 'Spatial Multiscale Analytical Science Hub',
        site_name: 'SMASH',
        description:
          'Spatial Analytical Science focuses on developing and applying ever-improving means of measuring and interpreting the composition, structure, and morphology of the spatial patterns and processes generated by natural and human systems.',
        img: 'https://geosmash.net/SMASHLogo.svg',
        img_size: { width: '400', height: '400' },
        locale: 'en_US',
        twitter: '@GEOSMASH',
        twitter_card: 'summary_large_image',
        theme_color: '#4f46e5',
      },
    ],
  ],
  build: {},
  tailwindcss: {
    cssPath: '~/assets/css/tailwind.css',
    configPath: 'tailwind.config.js',
    jit: true,
  },
  purgeIcons: {},
  image: {},
  netlify: {
    mergeSecurityHeaders: true,
    headers: {
      '/favicon.ico': ['Cache-Control: public, max-age=86400'],
    },
    redirects: [
      {
        from: '/overview',
        to: '/',
        status: 302,
        force: true,
      },
      {
        from: '/resources',
        to: '/',
        status: 302,
        force: true,
      },
    ],
  },
  humansTxt: {
    enabled: true,
    hideGenericMessagesInConsole: false,
    hideErrorsInConsole: false,
    keepDevelopersInformations: false,
    thanksTo: [
      {
        key: 'Matthew Tralka',
        value: 'Designer & Developer',
      },
      {
        key: 'Website',
        value: 'www.tralka.xyz',
      },
      false,
    ],
    site: [
      'SITE',
      {
        key: 'Last update',
        value: new Date().toLocaleDateString('en-US', {
          month: '2-digit',
          day: '2-digit',
          year: 'numeric',
        }),
      },
    ],
  },
}
